function(cgra_enable_warnings target)
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "Unknown target for warnings: ${target}")
  endif()

  target_compile_options("${target}" PRIVATE -Wall -Wextra -Wpedantic)
  if(CGRA_WARNINGS_AS_ERRORS)
    target_compile_options("${target}" PRIVATE -Werror)
  endif()
endfunction()
