function(cgra_enable_sanitizers target)
  if(NOT CGRA_ENABLE_ASAN AND NOT CGRA_ENABLE_UBSAN)
    return()
  endif()

  set(flags)
  if(CGRA_ENABLE_ASAN)
    list(APPEND flags -fsanitize=address)
  endif()
  if(CGRA_ENABLE_UBSAN)
    list(APPEND flags -fsanitize=undefined)
  endif()
  target_compile_options("${target}" PRIVATE ${flags})
  target_link_options("${target}" PRIVATE ${flags})
endfunction()
