#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Verify that Yosys infers one correctly shaped control memory per tile."""

from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

import run_yosys_slang as synth


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
RAW_DIR = REPO_ROOT / "reports/synthesis/raw"
EXPECTED_WIDTH = 128
EXPECTED_DEPTH = 256
EXPECTED_ADDRESS_BITS = 8


def yosys_script(
    target: str,
    rtl_files: list[str],
    selection_paths: dict[str, pathlib.Path],
) -> str:
    cfg = synth.TARGETS[target]
    base = "t:$mem_v2 c:*control_mem* %i"
    selectors = {
        "all": base,
        "width": f"{base} r:WIDTH={EXPECTED_WIDTH} %i",
        "depth": f"{base} r:SIZE={EXPECTED_DEPTH} %i",
        "address_bits": f"{base} r:ABITS={EXPECTED_ADDRESS_BITS} %i",
        "read_ports": f"{base} r:RD_PORTS=1 %i",
        "write_ports": f"{base} r:WR_PORTS=1 %i",
        "valid": (
            f"{base} r:WIDTH={EXPECTED_WIDTH} %i r:SIZE={EXPECTED_DEPTH} %i "
            f"r:ABITS={EXPECTED_ADDRESS_BITS} %i r:RD_PORTS=1 %i "
            "r:WR_PORTS=1 %i"
        ),
    }
    selection_commands = [
        f"select -write {selection_paths[name].as_posix()} {selector}"
        for name, selector in selectors.items()
    ]
    return "\n".join(
        [
            f"# Auto-generated by scripts/check_control_memory_shape.py for {target}.",
            "plugin -i slang",
            synth.read_slang_cmd(target, rtl_files),
            f"hierarchy -check -top {cfg['top']}",
            "proc",
            "flatten",
            "opt",
            "memory_collect",
            "check",
            f"select -module {cfg['top']}",
            *selection_commands,
            "",
        ]
    )


def read_selection(path: pathlib.Path) -> list[str]:
    if not path.exists():
        return []
    return sorted(
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    )


def run_target(target: str, yosys: str, rtl_files: list[str]) -> int:
    cfg = synth.TARGETS[target]
    expected_count = int(cfg["parameters"].get("ROWS", 4)) * int(
        cfg["parameters"].get("COLS", 4)
    )
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    report_path = RAW_DIR / f"control_memory_shape_{target}.json"

    with tempfile.TemporaryDirectory(prefix=f"cgra_control_mem_{target}_") as temp_dir:
        temp_path = pathlib.Path(temp_dir)
        selection_paths = {
            name: temp_path / f"{name}.txt"
            for name in (
                "all",
                "width",
                "depth",
                "address_bits",
                "read_ports",
                "write_ports",
                "valid",
            )
        }
        script_path = temp_path / "shape.ys"
        script_text = yosys_script(target, rtl_files, selection_paths)
        script_path.write_text(script_text, encoding="utf-8")
        command = [yosys, "-q", "-s", script_path.as_posix()]
        completed = subprocess.run(
            command,
            cwd=REPO_ROOT,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        selections = {
            name: read_selection(path) for name, path in selection_paths.items()
        }
        report_script = script_text.replace(temp_path.as_posix(), "<TEMP_DIR>")

    cells = selections["all"]
    shape_ok = len(cells) == expected_count and len(selections["valid"]) == expected_count
    passed = completed.returncode == 0 and shape_ok
    version = subprocess.run(
        [yosys, "-V"],
        cwd=REPO_ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    ).stdout.strip()
    report = {
        "schema": "cgra.control_memory_shape.v1",
        "target": target,
        "top": cfg["top"],
        "parameters": cfg["parameters"],
        "status": "CONTROL_MEMORY_SHAPE_PASS" if passed else "CONTROL_MEMORY_SHAPE_FAIL",
        "expected": {
            "count": expected_count,
            "width": EXPECTED_WIDTH,
            "depth": EXPECTED_DEPTH,
            "address_bits": EXPECTED_ADDRESS_BITS,
            "read_ports_per_bank": 1,
            "write_ports_per_bank": 1,
        },
        "actual": {
            "count": len(cells),
            "cell_names": cells,
            "valid_count": len(selections["valid"]),
            "valid_cell_names": selections["valid"],
            "parameter_match_counts": {
                name: len(selections[name])
                for name in (
                    "width",
                    "depth",
                    "address_bits",
                    "read_ports",
                    "write_ports",
                )
            },
        },
        "yosys_returncode": completed.returncode,
        "yosys_version": version,
        "source_filelist": synth.FILELIST.relative_to(REPO_ROOT).as_posix(),
        "source_filelist_sha256": synth.sha256_file(synth.FILELIST),
        "source_list_sha256": synth.sha256_text("\n".join(rtl_files) + "\n"),
        "source_contents_sha256": synth.sha256_sources(rtl_files),
        "script": report_script,
        "tool_output_tail": completed.stdout.splitlines()[-80:],
    }
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        f"{target}: {report['status']} "
        f"({len(cells)}/{expected_count} control banks; report={report_path.relative_to(REPO_ROOT)})"
    )
    if not passed:
        print(f"  cells: {cells}")
        print(f"  parameter matches: {report['actual']['parameter_match_counts']}")
    return 0 if passed else 1


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=("small", "default", "all"), default="all")
    args = parser.parse_args(argv)

    yosys = shutil.which("yosys")
    if yosys is None:
        print("yosys not found; source ../oss-cad-suite/environment", file=sys.stderr)
        return 2
    try:
        rtl_files = synth.read_filelist(synth.FILELIST)
    except ValueError as error:
        print(f"filelist error: {error}", file=sys.stderr)
        return 2
    targets = ("small", "default") if args.target == "all" else (args.target,)
    results = [run_target(target, yosys, rtl_files) for target in targets]
    return 1 if any(results) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
