#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Run oss-cad-suite Yosys/yosys-slang synthesis-sanity flows for T034S."""

import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
FILELIST = REPO_ROOT / "synth/rtl_files.f"
OUT_DIR = REPO_ROOT / "sim/synthesis"

TARGETS = {
    "small": {
        "top": "cgra_top",
        "parameters": {"ROWS": 2, "COLS": 2},
        "description": "small 2x2 cgra_top yosys-slang synthesis sanity target",
    },
    "default": {
        "top": "cgra_top",
        "parameters": {},
        "description": "default 4x4 cgra_top yosys-slang synthesis sanity target",
    },
}

SIM_ONLY_TOKENS = ("$fwrite", "$fopen", "$fflush", "$fatal", "CGRA_TRACE")


def read_filelist(path: pathlib.Path) -> list[str]:
    entries = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("+"):
            raise ValueError(f"line {line_no}: filelist options are not supported: {stripped}")
        rtl_path = REPO_ROOT / stripped
        if not rtl_path.exists():
            raise ValueError(f"line {line_no}: missing RTL source: {stripped}")
        entries.append(stripped)
    return entries


def sha256_file(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_sources(source_paths: list[str]) -> str:
    digest = hashlib.sha256()
    for source_path in source_paths:
        digest.update(source_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update((REPO_ROOT / source_path).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def run_cmd(cmd: list[str], timeout: int | None = None) -> tuple[int, str]:
    completed = subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=timeout,
    )
    return completed.returncode, completed.stdout


def yosys_version(yosys: str) -> tuple[int, str]:
    return run_cmd([yosys, "-V"], timeout=10)


def plugin_check(yosys: str) -> tuple[int, str]:
    return run_cmd([yosys, "-Q", "-p", "plugin -i slang; help read_slang"], timeout=30)


def read_slang_cmd(target: str, rtl_files: list[str]) -> str:
    cfg = TARGETS[target]
    parts = [
        "read_slang",
        "--std",
        "1800-2017",
        "-DSYNTHESIS",
        "--top",
        cfg["top"],
    ]
    for name, value in cfg["parameters"].items():
        parts.extend(["-G", f"{name}={value}"])
    parts.extend(rtl_files)
    return " ".join(parts)


def yosys_script(
    target: str,
    mode: str,
    rtl_files: list[str],
    stat_json: pathlib.Path | None,
) -> str:
    cfg = TARGETS[target]
    lines = [
        f"# Auto-generated by scripts/run_yosys_slang.py for T034S {mode}.",
        "# Requires oss-cad-suite Yosys with yosys-slang plugin in PATH.",
        "plugin -i slang",
        read_slang_cmd(target, rtl_files),
        f"hierarchy -check -top {cfg['top']}",
        "proc",
    ]
    if mode == "generic":
        lines.extend(
            [
                "opt",
                "memory_collect",
                "check",
                "stat -width",
            ]
        )
        if stat_json is not None:
            rel_stat = stat_json.relative_to(REPO_ROOT).as_posix()
            lines.append(f"tee -o {rel_stat} stat -json")
    else:
        lines.extend(["memory_collect", "check", "stat -width"])
    return "\n".join(lines) + "\n"


def simulation_io_mentions(output: str) -> list[str]:
    return [token for token in SIM_ONLY_TOKENS if token in output]

def parse_stat_json(path: pathlib.Path) -> dict[str, object]:
    if not path.exists():
        return {"available": False}
    text = path.read_text(encoding="utf-8")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        return {"available": False, "parse_error": str(exc)}

    modules = data.get("modules", {}) if isinstance(data, dict) else {}
    top = modules.get("\\cgra_top", {}) if isinstance(modules, dict) else {}
    cells = top.get("num_cells_by_type", {}) if isinstance(top, dict) else {}
    memory_cells = cells.get("$mem_v2", 0) if isinstance(cells, dict) else 0
    register_cell_types = {
        key: value for key, value in cells.items() if "dff" in key
    } if isinstance(cells, dict) else {}
    summary = {
        "available": True,
        "num_wires": top.get("num_wires"),
        "num_wire_bits": top.get("num_wire_bits"),
        "num_public_wires": top.get("num_pub_wires"),
        "num_public_wire_bits": top.get("num_pub_wire_bits"),
        "num_ports": top.get("num_ports"),
        "num_port_bits": top.get("num_port_bits"),
        "num_cells": top.get("num_cells"),
        "stat_num_memories": top.get("num_memories"),
        "stat_num_memory_bits": top.get("num_memory_bits"),
        "memory_cells": memory_cells,
        "register_cells": sum(register_cell_types.values()),
        "register_cell_types": register_cell_types,
        "cell_types": cells,
    }
    return summary


def classify(mode: str, returncode: int, output: str) -> tuple[str, str | None]:
    if returncode == 0:
        if mode == "generic":
            return "GENERIC_SYNTHESIS_STAT_PASS", None
        return "READ_SLANG_ELABORATION_PASS", None
    if "No such command" in output or "Can't load module" in output or "read_slang" in output and "help" in output and returncode != 0:
        return "SLANG_PLUGIN_UNAVAILABLE", "Yosys could not load or run yosys-slang read_slang; source the oss-cad-suite environment or repair plugin availability."
    return "FAILED_REPAIR_FINDING", "Yosys/yosys-slang flow did not complete; see log for the next precise unsupported construct or warning."


def run_flow(target: str, mode: str) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    yosys = shutil.which("yosys")
    if yosys is None:
        print("yosys not found in PATH", file=sys.stderr)
        return write_missing_tool(target, mode)

    try:
        rtl_files = read_filelist(FILELIST)
    except ValueError as exc:
        print(f"filelist error: {exc}", file=sys.stderr)
        return 2

    basename = f"slang_{mode}_{target}"
    log_path = OUT_DIR / f"{basename}.log"
    json_path = OUT_DIR / f"{basename}.json"
    script_path = OUT_DIR / f"{basename}.ys"
    stat_json_path = OUT_DIR / f"{basename}_stat.json" if mode == "generic" else None

    version_status, version_output = yosys_version(yosys)
    plugin_status, plugin_output = plugin_check(yosys)
    script = yosys_script(target, mode, rtl_files, stat_json_path)
    script_path.write_text(script, encoding="utf-8")
    cmd = [yosys, "-Q", "-s", script_path.relative_to(REPO_ROOT).as_posix()]
    returncode, output = run_cmd(cmd)
    status, finding = classify(mode, returncode, output)
    mentions = simulation_io_mentions(output)
    stat_summary = (
        parse_stat_json(stat_json_path)
        if stat_json_path is not None
        else {"available": False}
    )

    lines = [
        f"yosys-slang {mode} target: {target}",
        f"  description: {TARGETS[target]['description']}",
        f"  top: {TARGETS[target]['top']}",
        f"  parameters: {TARGETS[target]['parameters'] if TARGETS[target]['parameters'] else '<default>'}",
        f"  filelist: {FILELIST.relative_to(REPO_ROOT).as_posix()}",
        f"  filelist_sha256: {sha256_file(FILELIST)}",
        f"  source_list_sha256: {sha256_text(chr(10).join(rtl_files) + chr(10))}",
        f"  source_contents_sha256: {sha256_sources(rtl_files)}",
        "  define: SYNTHESIS",
        f"  yosys_path: {yosys}",
        f"  yosys_version_status: {version_status}",
        f"  yosys_version: {version_output.splitlines()[0] if version_output else '<no version output>'}",
        f"  plugin_check_status: {plugin_status}",
        f"  script: {script_path.relative_to(REPO_ROOT).as_posix()}",
        "  command: " + " ".join(cmd),
        "",
        "script:",
        script.rstrip(),
        "",
        "tool output:",
    ]
    if output.strip():
        lines.extend(output.rstrip().splitlines())
    else:
        lines.append("<no output>")
    lines.extend(
        [
            "",
            f"yosys_slang returncode: {returncode}",
            f"yosys_slang status: {status}",
            f"simulation_only_mentions_in_log: {', '.join(mentions) if mentions else '<none>'}",
        ]
    )
    if finding:
        lines.append(f"repair_finding: {finding}")
    if mode == "generic":
        lines.append(f"stat_json: {stat_json_path.relative_to(REPO_ROOT).as_posix() if stat_json_path else '<none>'}")
        lines.append("stat_summary: " + json.dumps(stat_summary, sort_keys=True))
    lines.append("note: generic Yosys statistics are synthesis-sanity resource evidence only, not technology-mapped area/timing/PPA.")

    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    record = {
        "schema": "cgra.yosys_slang_synthesis_sanity.v1",
        "target": target,
        "mode": mode,
        "description": TARGETS[target]["description"],
        "top": TARGETS[target]["top"],
        "parameters": TARGETS[target]["parameters"],
        "filelist": FILELIST.relative_to(REPO_ROOT).as_posix(),
        "filelist_sha256": sha256_file(FILELIST),
        "source_list_sha256": sha256_text("\n".join(rtl_files) + "\n"),
        "source_contents_sha256": sha256_sources(rtl_files),
        "define": "SYNTHESIS",
        "yosys_path": yosys,
        "yosys_version_status": version_status,
        "yosys_version_output": version_output,
        "plugin_check_status": plugin_status,
        "plugin_check_output": plugin_output,
        "script": script_path.relative_to(REPO_ROOT).as_posix(),
        "command": cmd,
        "returncode": returncode,
        "status": status,
        "repair_finding": finding,
        "simulation_only_mentions_in_log": mentions,
        "stat_json": stat_json_path.relative_to(REPO_ROOT).as_posix() if stat_json_path else None,
        "stat_summary": stat_summary,
        "log": log_path.relative_to(REPO_ROOT).as_posix(),
    }
    json_path.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0 if returncode == 0 else 1


def write_missing_tool(target: str, mode: str) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    basename = f"slang_{mode}_{target}"
    log_path = OUT_DIR / f"{basename}.log"
    json_path = OUT_DIR / f"{basename}.json"
    text = "\n".join(
        [
            f"yosys-slang {mode} target: {target}",
            "yosys_slang status: YOSYS_MISSING",
            "repair_finding: yosys was not found in PATH; source ../oss-cad-suite/environment and retry.",
        ]
    ) + "\n"
    log_path.write_text(text, encoding="utf-8")
    json_path.write_text(
        json.dumps(
            {
                "schema": "cgra.yosys_slang_synthesis_sanity.v1",
                "target": target,
                "mode": mode,
                "status": "YOSYS_MISSING",
                "repair_finding": "yosys was not found in PATH; source ../oss-cad-suite/environment and retry.",
            },
            indent=2,
            sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )
    print(text, end="")
    return 1


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=sorted(TARGETS), required=True)
    parser.add_argument("--mode", choices=("elaborate", "generic"), required=True)
    args = parser.parse_args(argv)
    return run_flow(args.target, args.mode)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
