#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Run T035 ASAP7 technology mapping and preserve raw area/resource reports."""

import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
import sys

import run_yosys_slang as sanity

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
REPORT_DIR = REPO_ROOT / "reports/synthesis"
RAW_DIR = REPORT_DIR / "raw"
ASAP7_ROOT = REPO_ROOT / "synth/asap7/v28/RVT_TT"
ASAP7_LIBERTY = ASAP7_ROOT / "lib/asap7sc7p5t_RVT_TT_nldm_merged.lib"
ASAP7_LEF = ASAP7_ROOT / "lef/asap7sc7p5t_28_R_1x_220121a.lef"
ASAP7_MANIFEST = ASAP7_ROOT / "manifest.json"


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run_command(command: list[str]) -> tuple[int, str]:
    completed = subprocess.run(
        command,
        cwd=REPO_ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return completed.returncode, completed.stdout


def run_command_to_log(command: list[str], log_path: pathlib.Path) -> int:
    with log_path.open("w", encoding="utf-8") as log:
        completed = subprocess.run(
            command,
            cwd=REPO_ROOT,
            check=False,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
        )
    return completed.returncode


def load_json(path: pathlib.Path) -> dict[str, object] | None:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def stat_summary(path: pathlib.Path, top: str) -> dict[str, object]:
    data = load_json(path) or {}
    modules = data.get("modules", {})
    module = modules.get(f"\\{top}", {}) if isinstance(modules, dict) else {}
    cells = module.get("num_cells_by_type", {}) if isinstance(module, dict) else {}
    cell_types = cells if isinstance(cells, dict) else {}
    internal = {
        name: count
        for name, count in cell_types.items()
        if isinstance(name, str) and name.startswith("$")
    }
    mapped = {
        name: count
        for name, count in cell_types.items()
        if isinstance(name, str) and not name.startswith("$")
    }
    register_cells = sum(
        count
        for name, count in mapped.items()
        if "dff" in name.lower() or "sdff" in name.lower()
    )
    memory_cells = sum(
        count for name, count in internal.items() if "mem" in name.lower()
    )
    return {
        "stat_available": bool(module),
        "total_cells": module.get("num_cells") if isinstance(module, dict) else None,
        "technology_area": module.get("area") if isinstance(module, dict) else None,
        "mapped_cells": sum(mapped.values()),
        "unmapped_cells": sum(internal.values()),
        "unmapped_cell_types": internal,
        "register_cells": register_cells,
        "memory_cells": memory_cells,
        "cell_types": cell_types,
    }


def yosys_script(target: str, rtl_files: list[str], paths: dict[str, pathlib.Path]) -> str:
    cfg = sanity.TARGETS[target]
    relative = {name: path.relative_to(REPO_ROOT).as_posix() for name, path in paths.items()}
    return "\n".join(
        [
            f"# Auto-generated by scripts/run_synth_area.py for T035 target {target}.",
            "# ASAP7 v28 7.5-track RVT/TT NLDM technology mapping.",
            "plugin -i slang",
            sanity.read_slang_cmd(target, rtl_files),
            f"hierarchy -check -top {cfg['top']}",
            "proc",
            "flatten",
            "opt",
            "memory_collect",
            "techmap */t:* */t:$mem_v2 %d",
            "opt",
            "techmap */t:* */t:$mem_v2 %d",
            "opt",
            "dffunmap",
            f"dfflibmap -liberty {relative['liberty']}",
            f"abc -fast -liberty {relative['liberty']}",
            "clean",
            f"tee -o {relative['stat']} stat -json -liberty {relative['liberty']}",
            f"stat -liberty {relative['liberty']}",
            "",
        ]
    )


def record_missing_prerequisite(target: str, finding: str) -> int:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    basename = f"asap7_area_{target}"
    for suffix in (".log", ".ys", "_stat.json"):
        (RAW_DIR / f"{basename}{suffix}").unlink(missing_ok=True)
    record_path = RAW_DIR / f"asap7_area_{target}.json"
    record_path.write_text(
        json.dumps(
            {
                "schema": "cgra.asap7_area_report.v1",
                "target": target,
                "status": "PREREQUISITE_MISSING",
                "repair_finding": finding,
            },
            indent=2,
            sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )
    print(f"{target}: {finding}", file=sys.stderr)
    return 1


def run_target(target: str) -> int:
    if not ASAP7_LIBERTY.exists() or not ASAP7_MANIFEST.exists():
        return record_missing_prerequisite(
            target,
            "ASAP7 cache is missing; run make synth-fetch-asap7 with a 7z-compatible extractor.",
        )
    yosys = shutil.which("yosys")
    if yosys is None:
        return record_missing_prerequisite(
            target, "yosys is missing; source ../oss-cad-suite/environment and retry."
        )
    try:
        rtl_files = sanity.read_filelist(sanity.FILELIST)
    except ValueError as error:
        return record_missing_prerequisite(target, str(error))

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    basename = f"asap7_area_{target}"
    paths = {
        "liberty": ASAP7_LIBERTY,
        "script": RAW_DIR / f"{basename}.ys",
        "stat": RAW_DIR / f"{basename}_stat.json",
    }
    paths["stat"].unlink(missing_ok=True)
    script = yosys_script(target, rtl_files, paths)
    paths["script"].write_text(script, encoding="utf-8")
    command = [yosys, "-Q", "-s", paths["script"].relative_to(REPO_ROOT).as_posix()]
    log_path = RAW_DIR / f"{basename}.log"
    returncode = run_command_to_log(command, log_path)

    summary = stat_summary(paths["stat"], sanity.TARGETS[target]["top"])
    residual_types = summary["unmapped_cell_types"]
    residual_memory_only = bool(residual_types) and all(
        "mem" in name.lower() for name in residual_types
    )
    reportable_area = (
        returncode == 0
        and summary["stat_available"]
        and summary["technology_area"] is not None
    )
    if reportable_area and summary["unmapped_cells"] == 0:
        status = "TECHNOLOGY_MAPPED_AREA_PASS"
    elif reportable_area and residual_memory_only:
        status = "TECHNOLOGY_MAPPED_AREA_PARTIAL_MEMORY_UNMAPPED"
    else:
        status = "TECHNOLOGY_MAPPING_FAILED"
    finding = None
    if returncode != 0:
        finding = "Yosys/ABC did not complete; inspect the matching raw log."
    elif residual_memory_only:
        finding = (
            "ASAP7 standard-cell mapping leaves inferred $mem_v2 storage cells "
            "unmapped because no SRAM macro was selected; reported area excludes them."
        )
    elif summary["unmapped_cells"]:
        finding = "Technology mapping left non-memory Yosys cells; area is incomplete."
    elif summary["technology_area"] is None:
        finding = "Yosys stat did not provide technology area."

    manifest = load_json(ASAP7_MANIFEST) or {}
    record = {
        "schema": "cgra.asap7_area_report.v1",
        "target": target,
        "top": sanity.TARGETS[target]["top"],
        "parameters": sanity.TARGETS[target]["parameters"],
        "define": "SYNTHESIS",
        "source_filelist": sanity.FILELIST.relative_to(REPO_ROOT).as_posix(),
        "source_filelist_sha256": sha256(sanity.FILELIST),
        "source_list_sha256": hashlib.sha256(
            ("\n".join(rtl_files) + "\n").encode("utf-8")
        ).hexdigest(),
        "source_contents_sha256": sanity.sha256_sources(rtl_files),
        "technology": {
            "name": "ASAP7 7nm predictive PDK",
            "standard_cell_library": "asap7sc7p5t_28",
            "corner": manifest.get("corner"),
            "liberty_model": manifest.get("liberty_model"),
            "repository": manifest.get("repository"),
            "repository_revision": manifest.get("repository_revision"),
            "standard_cell_revision": manifest.get("standard_cell_revision"),
            "liberty": paths["liberty"].relative_to(REPO_ROOT).as_posix(),
            "liberty_sha256": sha256(paths["liberty"]),
            "lef": ASAP7_LEF.relative_to(REPO_ROOT).as_posix() if ASAP7_LEF.exists() else None,
        },
        "tool": {
            "yosys_path": yosys,
            "yosys_version": run_command([yosys, "-V"])[1].strip(),
            "yosys_slang_plugin_status": run_command(
                [yosys, "-Q", "-p", "plugin -i slang; help read_slang"]
            )[0],
            "openroad_path": shutil.which("openroad"),
            "openroad_status": "NOT_RUN_TOOL_UNAVAILABLE"
            if shutil.which("openroad") is None
            else "NOT_RUN_T035_HAS_NO_PHYSICAL_BACKEND_STEP",
        },
        "command": command,
        "script": paths["script"].relative_to(REPO_ROOT).as_posix(),
        "raw_log": log_path.relative_to(REPO_ROOT).as_posix(),
        "raw_stat": paths["stat"].relative_to(REPO_ROOT).as_posix(),
        "mapped_netlist": None,
        "returncode": returncode,
        "status": status,
        "repair_finding": finding,
        "summary": summary,
    }
    (RAW_DIR / f"{basename}.json").write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"{target}: {status}")
    return 0 if status != "TECHNOLOGY_MAPPING_FAILED" else 1


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=("small", "default", "all"), default="all")
    args = parser.parse_args(argv)
    targets = ("small", "default") if args.target == "all" else (args.target,)
    results = [run_target(target) for target in targets]
    return 0 if not any(results) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
