#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Run standalone FN-CACTI storage area and power characterization."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys
from typing import Any

import fn_cacti_common as common

CLOCK_HZ = 100_000_000
SCENARIO = "all_declared_ports_once_per_10ns_cycle"
FNC_DEVICE_NODE_UM = 0.014
FNC_WIRE_NODE_UM = 0.007
FNC_OPERATING_VOLTAGE = 0.7
FNC_MINIMUM_CAPACITY_BYTES = 64
PROXY_STATUS = "MEMORY_PPA_COMPLETE_ANALYTICAL_PROXY"


def architectural_size_bytes(storage: dict[str, Any]) -> int:
    return (storage["width_bits"] * storage["depth"] + 7) // 8


def modeled_size_bytes(storage: dict[str, Any]) -> int:
    return max(architectural_size_bytes(storage), FNC_MINIMUM_CAPACITY_BYTES)


def class_model_status(storage: dict[str, Any]) -> str:
    if modeled_size_bytes(storage) != architectural_size_bytes(storage):
        return "MODELED_WITH_ASYNC_READ_AND_MINIMUM_CAPACITY_PADDING_APPROXIMATION"
    return "MODELED_WITH_EXPLICIT_ASYNC_READ_APPROXIMATION"


def model_basis() -> dict[str, Any]:
    return {
        "architectural_technology": "ASAP7_7NM",
        "fn_cacti_transistor_type": "finfet",
        "fn_cacti_device_node_um": FNC_DEVICE_NODE_UM,
        "fn_cacti_wire_node_um": FNC_WIRE_NODE_UM,
        "fn_cacti_interconnects": "ASAP7",
        "operating_voltage_v": FNC_OPERATING_VOLTAGE,
        "scaling_applied": False,
        "logic_area_compatibility": "INCOMPATIBLE_WITH_ASAP7_7NM_1X_LOGIC_AREA",
        "reason": (
            "the supplied FN-CACTI README documents 14 nm device support; its 7 nm "
            "device-node probe aborts in component.cc, so no 7 nm device proxy is accepted"
        ),
    }


def write_text(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def run_to_log(command: list[str], cwd: pathlib.Path, log_path: pathlib.Path) -> int:
    with log_path.open("w", encoding="utf-8") as log:
        completed = subprocess.run(
            command,
            cwd=cwd,
            check=False,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
        )
    return completed.returncode


def config_text(storage: dict[str, Any], device_node_um: float = FNC_DEVICE_NODE_UM) -> str:
    width = storage["width_bits"]
    depth = storage["depth"]
    size_bytes = modeled_size_bytes(storage)
    block_bytes = max(1, (width + 7) // 8)
    return "\n".join(
        [
            "# Auto-generated by scripts/run_fn_cacti.py.",
            "# FN-CACTI FinFET device/wire assumptions are recorded in the manifest.",
            "-transistor type - \"finfet\"",
            f"-technology node {device_node_um:.3f}",
            f"-wire technology node {FNC_WIRE_NODE_UM:.3f}",
            f"-operating voltage {FNC_OPERATING_VOLTAGE:.1f}",
            f"-DVS(V): {FNC_OPERATING_VOLTAGE:.1f}",
            "-temperature 300",
            f"-size {size_bytes}",
            f"-block size {block_bytes}",
            "-associativity 1",
            "-ncfet - \"false\"",
            "-read-write port 0",
            f"-exclusive read port {storage['read_ports']}",
            f"-exclusive write port {storage['write_ports']}",
            "-single ended read ports 0",
            "-search port 0",
            "-cache model - \"UCA\"",
            "-uca bank 1",
            "-nuca bank count 0",
            f"-bus width {width}",
            "-memory type \"ram\"",
            "-tag size \"default\"",
            "-access mode - \"normal\"",
            "-optimize - \"ED\"",
            "-design objective (weight delay, dynamic power, leakage power, cycle time, area) 0:0:0:100:0",
            "-deviate (delay, dynamic power, leakage power, cycle time, area) 20:100000:100000:100000:100000",
            "-NUCAdesign objective (weight delay, dynamic power, leakage power, cycle time, area) 100:100:0:0:100",
            "-NUCAdeviate (delay, dynamic power, leakage power, cycle time, area) 10:10000:10000:10000:10000",
            "-interconnects - \"ASAP7\"",
            "-wire signalling - \"Low_swing\"",
            "-Wire inside mat - \"semi-global\"",
            "-Wire outside mat - \"global\"",
            "-Interconnect projection - \"aggressive\"",
            "-Core count 1",
            "-Cache level - \"L3\"",
            "-Add ECC - \"false\"",
            "-Print level (DETAILED, CONCISE) - \"DETAILED\"",
            "-Print input parameters - \"true\"",
            "-Force cache config - \"false\"",
            "-Ndwl 2",
            "-Ndbl 8",
            "-Nspd 2",
            "-Ndcm 8",
            "-Ndsam1 1",
            "-Ndsam2 1",
            "-Ntwl 2",
            "-Ntbl 2",
            "-Ntspd 1",
            "-Ntcm 1",
            "-Ntsam1 2",
            "-Ntsam2 1",
            "-page size (bits) 0",
            "-burst length 1",
            "-internal prefetch width 1",
            "",
        ]
    )


def storage_mapping(storage: dict[str, Any]) -> dict[str, Any]:
    architectural_bytes = architectural_size_bytes(storage)
    fn_cacti_bytes = modeled_size_bytes(storage)
    return {
        "capacity_bits": storage["depth"] * storage["width_bits"],
        "architectural_size_bytes": architectural_bytes,
        "fn_cacti_size_bytes": fn_cacti_bytes,
        "capacity_representation": (
            "NATIVE_EXACT_CAPACITY"
            if fn_cacti_bytes == architectural_bytes
            else "PADDED_TO_FNC_ACTI_MINIMUM_64_BYTES_CONSERVATIVE_PROXY"
        ),
        "capacity_padding_bytes": fn_cacti_bytes - architectural_bytes,
        "capacity_padding_factor": fn_cacti_bytes / architectural_bytes,
        "fn_cacti_bus_width_bits": storage["width_bits"],
        "fn_cacti_ports": {
            "read_write": 0,
            "exclusive_read": storage["read_ports"],
            "exclusive_write": storage["write_ports"],
        },
        "port_model": "NATIVE_EXCLUSIVE_READ_WRITE_PORT_COUNTS",
        "rtl_read_mode": storage["read_mode"],
        "rtl_write_mode": storage["write_mode"],
        "read_timing_semantics": "ASYNC_READ_NOT_TIMING_CHARACTERIZED_BY_FN_CACTI",
        "model_status": class_model_status(storage),
        "technology": model_basis(),
    }


def scenario(metrics: dict[str, float], instances: int, storage: dict[str, Any]) -> dict[str, Any]:
    total_area_um2 = metrics["area_um2"] * instances
    total_leakage_mw = metrics["leakage_mw"] * instances
    reads_per_second = storage["read_ports"] * CLOCK_HZ * instances
    writes_per_second = storage["write_ports"] * CLOCK_HZ * instances
    read_dynamic_mw = metrics["read_energy_pj"] * reads_per_second / 1_000_000_000.0
    write_dynamic_mw = metrics["write_energy_pj"] * writes_per_second / 1_000_000_000.0
    return {
        "clock_hz": CLOCK_HZ,
        "activity_name": SCENARIO,
        "read_accesses_per_second": reads_per_second,
        "write_accesses_per_second": writes_per_second,
        "formula": "P_dynamic_mW = E_pJ_per_access * accesses_per_second / 1e9",
        "per_instance": metrics,
        "target_total": {
            "instances": instances,
            "area_um2": total_area_um2,
            "area_mm2": total_area_um2 / 1_000_000.0,
            "leakage_mw": total_leakage_mw,
            "read_dynamic_mw": read_dynamic_mw,
            "write_dynamic_mw": write_dynamic_mw,
            "dynamic_mw": read_dynamic_mw + write_dynamic_mw,
            "total_mw": total_leakage_mw + read_dynamic_mw + write_dynamic_mw,
        },
        "idle": {
            "read_accesses_per_second": 0,
            "write_accesses_per_second": 0,
            "dynamic_mw": 0.0,
            "total_mw": total_leakage_mw,
        },
    }


def standalone_preflight(output_root: pathlib.Path) -> tuple[list[dict[str, str]], dict[str, Any]]:
    inventory_errors, inventory = common.validate_inventory()
    snapshot = common.fn_cacti_snapshot()
    blockers = [{"code": "INVENTORY_VALIDATION_FAILED", "detail": error} for error in inventory_errors]
    if not common.FNC_ROOT.is_dir():
        blockers.append({"code": "FNC_ACTI_ROOT_MISSING", "detail": common.relative(common.FNC_ROOT)})
    if snapshot["live_pcacti_paths"]:
        blockers.append(
            {
                "code": "PCACTI_LIVE_DEPENDENCY_PRESENT",
                "detail": ", ".join(snapshot["live_pcacti_paths"]),
            }
        )
    missing = snapshot["required_source_missing"]
    if not common.FNC_EXECUTABLE.is_file() and missing:
        blockers.append(
            {
                "code": "FNC_ACTI_INCOMPLETE_STANDALONE_SNAPSHOT",
                "detail": "missing sources: " + ", ".join(missing),
            }
        )
    build = {"attempted": False, "returncode": None, "command": None, "log": None}
    if common.FNC_EXECUTABLE.is_file() and not os.access(common.FNC_EXECUTABLE, os.X_OK):
        blockers.append(
            {
                "code": "FNC_ACTI_EXECUTABLE_PERMISSION_MISSING",
                "detail": common.relative(common.FNC_EXECUTABLE),
            }
        )
    if not blockers and not common.FNC_EXECUTABLE.is_file():
        build_log = output_root / "standalone_build.log"
        command = ["make", "-j2"]
        build["attempted"] = True
        build["command"] = command
        build["log"] = common.relative(build_log)
        build["returncode"] = run_to_log(command, common.FNC_SOURCE, build_log)
        if build["returncode"] != 0 or not common.FNC_EXECUTABLE.is_file():
            blockers.append(
                {
                    "code": "FNC_ACTI_STANDALONE_BUILD_FAILED",
                    "detail": "direct fncacti make failed; inspect standalone_build.log",
                }
            )
    snapshot = common.fn_cacti_snapshot()
    preflight = {
        "schema": "cgra.fn_cacti_preflight.v1",
        "inventory_validation": {"errors": inventory_errors, "details": inventory},
        "fn_cacti": snapshot,
        "pcacti_used": False,
        "forbidden_commands": ["fncacti_patch.sh", "pcacti.tgz", "pcacti.tar"],
        "build": build,
        "blockers": blockers,
    }
    return blockers, preflight


def device_node_probe(output_root: pathlib.Path, storage: dict[str, Any]) -> tuple[dict[str, Any] | None, str | None]:
    """Record that this exact supplied binary cannot model the requested 7 nm devices."""
    probe_root = output_root / "device_node_probe"
    probe_root.mkdir(parents=True, exist_ok=True)
    config_path = probe_root / "device_7nm_probe.cfg"
    log_path = probe_root / "device_7nm_probe.log"
    report_path = probe_root / "pcacti_report.txt"
    write_text(config_path, config_text(storage, device_node_um=0.007))
    report_path.unlink(missing_ok=True)
    command = [str(common.FNC_EXECUTABLE), "-infile", config_path.name]
    returncode = run_to_log(command, probe_root, log_path)
    log_text = log_path.read_text(encoding="utf-8", errors="replace")
    assertion = "Assertion" in log_text or "assert" in log_text
    if returncode == 0 or report_path.exists() or not assertion:
        return None, "7 nm device-node probe did not fail with the expected FN-CACTI assertion"
    return {
        "status": "UNUSABLE_ASSERTION",
        "requested_device_node_um": 0.007,
        "command": command,
        "returncode": returncode,
        "assertion_observed": assertion,
        "fresh_report_produced": False,
        "config": common.artifact(config_path),
        "raw_log": common.artifact(log_path),
    }, None


def run_class(
    target_root: pathlib.Path, storage: dict[str, Any], target: str
) -> tuple[dict[str, Any] | None, str | None]:
    name = storage["name"]
    class_root = target_root / name
    class_root.mkdir(parents=True, exist_ok=True)
    config_path = class_root / f"{name}.cfg"
    raw_log = class_root / "fn_cacti.log"
    raw_report = class_root / "pcacti_report.txt"
    write_text(config_path, config_text(storage))
    raw_report.unlink(missing_ok=True)
    command = [str(common.FNC_EXECUTABLE), "-infile", config_path.name]
    returncode = run_to_log(command, class_root, raw_log)
    if returncode != 0:
        return None, f"{name}: FN-CACTI returned {returncode}"
    if not raw_report.is_file() or raw_report.stat().st_size == 0:
        return None, f"{name}: FN-CACTI did not produce pcacti_report.txt"
    log_text = raw_log.read_text(encoding="utf-8", errors="replace")
    if any(marker in log_text for marker in ("ERROR:", "Assertion", "assertion", "Cache size must")):
        return None, f"{name}: FN-CACTI log reports an invalid configuration"
    try:
        raw = common.parse_report(raw_report)
        metrics = common.normalized_metrics(raw)
    except ValueError as error:
        return None, f"{name}: {error}"
    inventory = storage["instances"]
    instances = inventory.get(target) if isinstance(inventory, dict) else None
    if not isinstance(instances, int) or instances <= 0:
        return None, f"{name}: missing positive instance count for {target}"
    record = {
        "name": name,
        "model_status": class_model_status(storage),
        "inventory": storage,
        "parameter_mapping": storage_mapping(storage),
        "config": common.artifact(config_path),
        "raw_log": common.artifact(raw_log),
        "raw_report": common.artifact(raw_report),
        "command": command,
        "returncode": returncode,
        "raw_metrics": raw,
        "normalized_metrics": metrics,
        "power_scenarios": scenario(metrics, instances, storage),
    }
    common.write_json(class_root / "result.json", record)
    record["result"] = common.artifact(class_root / "result.json")
    return record, None


def aggregate_classes(classes: list[dict[str, Any]]) -> dict[str, Any]:
    total = {
        "area_um2": 0.0,
        "area_mm2": 0.0,
        "leakage_mw": 0.0,
        "read_dynamic_mw": 0.0,
        "write_dynamic_mw": 0.0,
        "dynamic_mw": 0.0,
        "total_mw": 0.0,
    }
    for record in classes:
        item = record["power_scenarios"]["target_total"]
        for key in total:
            total[key] += item[key]
    return {
        "scenario": SCENARIO,
        "clock_hz": CLOCK_HZ,
        "total": total,
        "idle_total_mw": total["leakage_mw"],
        "coverage": "ALL_FIVE_ARCHITECTURAL_STORAGE_CLASSES",
    }


def refresh_logic_area(run_kind: str) -> tuple[dict[str, Any] | None, str | None]:
    logic_root = common.REPORT_ROOT / "logic_area" / run_kind
    logic_root.mkdir(parents=True, exist_ok=True)
    log_path = logic_root / "logic_area_refresh.log"
    command = [
        sys.executable,
        "scripts/run_synth_area.py",
        "--target",
        "all",
        "--report-dir",
        common.relative(logic_root),
    ]
    returncode = run_to_log(command, common.REPO_ROOT, log_path)
    records: dict[str, Any] = {}
    for target in common.TARGETS:
        path = logic_root / "raw" / f"asap7_area_{target}.json"
        if not path.is_file():
            return None, f"logic area refresh did not write {common.relative(path)}"
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            return None, f"logic area refresh wrote invalid JSON for {target}: {error}"
        if not isinstance(value, dict):
            return None, f"logic area refresh report for {target} is malformed"
        if value.get("status") != "TECHNOLOGY_MAPPED_AREA_PARTIAL_MEMORY_UNMAPPED":
            return None, f"logic area refresh status for {target} is {value.get('status')!r}"
        summary = value.get("summary")
        area = summary.get("technology_area") if isinstance(summary, dict) else None
        if not isinstance(area, (int, float)) or area <= 0.0:
            return None, f"logic area refresh lacks technology area for {target}"
        records[target] = {"report": common.artifact(path), "technology_area_um2": float(area)}
    if returncode != 0:
        return None, "logic area refresh command failed; inspect logic_area_refresh.log"
    return {
        "command": command,
        "returncode": returncode,
        "log": common.artifact(log_path),
        "units": "ASAP7_1X_LIBERTY_AREA_UM2",
        "targets": records,
    }, None


def memory_inclusive_area(target_results: list[dict[str, Any]], logic_area: dict[str, Any]) -> dict[str, Any]:
    separated: list[dict[str, Any]] = []
    logic_targets = logic_area["targets"]
    for item in target_results:
        target = item["target"]
        logic_um2 = logic_targets[target]["technology_area_um2"]
        memory_um2 = item["aggregate"]["total"]["area_um2"]
        separated.append(
            {
                "target": target,
                "logic_area_um2": logic_um2,
                "storage_proxy_area_um2": memory_um2,
                "storage_proxy_area_mm2": memory_um2 / 1_000_000.0,
                "mixed_node_arithmetic_sum_um2": logic_um2 + memory_um2,
                "mixed_node_arithmetic_sum_mm2": (logic_um2 + memory_um2) / 1_000_000.0,
                "total_area_um2": None,
                "total_area_mm2": None,
            }
        )
    return {
        "status": "MEMORY_INCLUSIVE_AREA_UNAVAILABLE",
        "reason": "FN_CACTI_14NM_DEVICE_PROXY_IS_INCOMPATIBLE_WITH_ASAP7_7NM_1X_LOGIC_AREA",
        "scaling_applied": False,
        "logic_area_units": logic_area["units"],
        "storage_proxy_area_units": "FN_CACTI_14NM_DEVICE_MM2_NORMALIZED_TO_UM2",
        "mixed_node_arithmetic_sum_status": "REPORTING_BREAKDOWN_ONLY_NOT_A_NODE_NORMALIZED_PHYSICAL_TOTAL",
        "accounting_boundary": "mapped_standard_cells_and_storage_proxy_are_reported_separately; excludes simulation initialization arrays",
        "targets": separated,
    }


def target_run(target_root: pathlib.Path, target: str, inventory: dict[str, Any]) -> tuple[dict[str, Any] | None, list[str]]:
    classes = inventory.get("classes")
    if not isinstance(classes, list):
        return None, ["inventory classes are malformed"]
    by_name = {item["name"]: item for item in classes if isinstance(item, dict) and isinstance(item.get("name"), str)}
    records: list[dict[str, Any]] = []
    errors: list[str] = []
    for name in common.CLASS_ORDER:
        record, error = run_class(target_root, by_name[name], target)
        if error is not None:
            errors.append(error)
        elif record is not None:
            records.append(record)
    if errors:
        return None, errors
    result = {
        "target": target,
        "status": PROXY_STATUS,
        "classes": records,
        "aggregate": aggregate_classes(records),
    }
    common.write_json(target_root / "target_manifest.json", result)
    result["manifest"] = common.artifact(target_root / "target_manifest.json")
    return result, []


def write_summary(manifest: dict[str, Any], output_root: pathlib.Path) -> None:
    lines = ["# FN-CACTI Storage Area/Power Summary", ""]
    lines += [
        f"- Status: `{manifest['status']}`",
        "- Technology basis: FN-CACTI 14 nm FinFET devices, 7 nm ASAP7 wires/interconnects; no geometric or PPA scaling was applied.",
        "- Area combination: `MEMORY_INCLUSIVE_AREA_UNAVAILABLE`; the report includes a clearly labeled mixed-node arithmetic sum, not a node-normalized physical total.",
        "- Power is analytical: leakage plus explicit 100 MHz all-port bounded-access scenarios.",
        "- Whole-design power: `TOTAL_POWER_NOT_COMBINABLE` because the ABC values lack a common SI/activity basis.",
        "",
    ]
    if manifest["status"] != PROXY_STATUS:
        lines.append("## Blockers")
        lines.append("")
        for blocker in manifest["blockers"]:
            lines.append(f"- `{blocker['code']}`: {blocker['detail']}")
    else:
        lines += ["## Storage Totals", "", "| Target | Area (um^2) | Area (mm^2) | Leakage (mW) | Bounded-access total (mW) |", "| --- | ---: | ---: | ---: | ---: |"]
        for item in manifest["targets"]:
            total = item["aggregate"]["total"]
            lines.append(
                f"| {item['target']} | {total['area_um2']:.6f} | {total['area_mm2']:.9f} | "
                f"{total['leakage_mw']:.9f} | {total['total_mw']:.9f} |"
            )
        lines += [
            "",
            "## Mixed-Node Area Breakdown",
            "",
            "| Target | ASAP7 logic (um^2) | FN-CACTI storage proxy (um^2) | Arithmetic sum (um^2) |",
            "| --- | ---: | ---: | ---: |",
        ]
        for item in manifest["memory_inclusive_area"]["targets"]:
            lines.append(
                f"| {item['target']} | {item['logic_area_um2']:.6f} | "
                f"{item['storage_proxy_area_um2']:.6f} | "
                f"{item['mixed_node_arithmetic_sum_um2']:.6f} |"
            )
        lines += [
            "",
            "The arithmetic sum mixes ASAP7 7 nm logic with a 14 nm-device/7 nm-wire storage proxy and is provided only as a paper-style component breakdown.",
        ]
        lines += ["", "## Per-Class Results", "", "| Target | Class | Modeled bytes | Area (um^2)/instance | Leakage (mW)/instance | Read energy (pJ) | Write energy (pJ) |", "| --- | --- | ---: | ---: | ---: | ---: | ---: |"]
        for target_item in manifest["targets"]:
            for class_item in target_item["classes"]:
                mapping = class_item["parameter_mapping"]
                metrics = class_item["normalized_metrics"]
                lines.append(
                    f"| {target_item['target']} | {class_item['name']} | {mapping['fn_cacti_size_bytes']} | "
                    f"{metrics['area_um2']:.6f} | {metrics['leakage_mw']:.9f} | "
                    f"{metrics['read_energy_pj']:.9f} | {metrics['write_energy_pj']:.9f} |"
                )
        lines += ["", "## Combination Status", ""]
        lines.append(f"- Area: `{manifest['memory_inclusive_area']['status']}`")
        lines.append(f"- Power: `{manifest['whole_design_power_status']}`")
    text = "\n".join(lines) + "\n"
    write_text(output_root / "memory_area_power_summary.md", text)
    if manifest["run_kind"] == "canonical":
        write_text(common.REPO_ROOT / "reports/synthesis/memory_area_power_summary.md", text)


def finalize_manifest(manifest: dict[str, Any], output_root: pathlib.Path) -> None:
    write_summary(manifest, output_root)
    manifest["summary"] = common.artifact(output_root / "memory_area_power_summary.md")
    common.write_json(output_root / "run_manifest.json", manifest)


def run(args: argparse.Namespace) -> int:
    output_root = common.REPORT_ROOT / ("replay" if args.replay else "canonical")
    output_root.mkdir(parents=True, exist_ok=True)
    blockers, preflight = standalone_preflight(output_root)
    preflight_path = output_root / "standalone_preflight.json"
    common.write_json(preflight_path, preflight)
    manifest: dict[str, Any] = {
        "schema": "cgra.fn_cacti.v1",
        "run_kind": "replay" if args.replay else "canonical",
        "status": "BLOCKED_PREREQUISITE" if blockers else "IN_PROGRESS",
        "blockers": blockers,
        "pcacti_used": False,
        "source_snapshot": common.source_snapshot(),
        "fn_cacti": common.fn_cacti_snapshot(),
        "standalone_preflight": common.artifact(preflight_path),
        "targets": [],
        "whole_design_power_status": "TOTAL_POWER_NOT_COMBINABLE",
        "model_basis": model_basis(),
        "limitations": [
            "FN-CACTI is an analytical memory estimator, not an ASAP7 SRAM compiler or signoff flow.",
            "This supplied FN-CACTI snapshot is usable only as a 14 nm device / 7 nm wire proxy; any logic-plus-storage arithmetic sum is a mixed-node reporting breakdown, not a node-normalized physical total.",
            "FN-CACTI has a 64-byte minimum cache size; predicate_rf is conservatively padded from 2 bytes to 64 bytes per instance.",
            "RTL asynchronous reads are reported as an explicit model approximation, not cycle timing proof.",
            "Raw ABC power units and activity do not permit whole-design SI power aggregation.",
        ],
    }
    if blockers:
        finalize_manifest(manifest, output_root)
        print("FN_CACTI_BLOCKED_PREREQUISITE", file=sys.stderr)
        return 2
    inventory = common.load_inventory()
    probe, probe_error = device_node_probe(output_root, next(item for item in inventory["classes"] if item["name"] == "control_mem"))
    if probe_error is not None or probe is None:
        manifest["status"] = "FLOW_FAILED"
        manifest["blockers"] = [{"code": "FNC_ACTI_7NM_PROBE_UNEXPECTED", "detail": probe_error or "missing probe evidence"}]
        finalize_manifest(manifest, output_root)
        print("FN_CACTI_FLOW_FAILED", file=sys.stderr)
        return 1
    manifest["device_node_probe"] = probe
    targets = tuple(common.TARGETS) if args.target == "all" else (args.target,)
    failures: list[str] = []
    for target in targets:
        result, errors = target_run(output_root / target, target, inventory)
        if errors:
            failures.extend(errors)
        elif result is not None:
            manifest["targets"].append(result)
    if failures:
        manifest["status"] = "FLOW_FAILED"
        manifest["blockers"] = [{"code": "FNC_ACTI_MODEL_RUN_FAILED", "detail": error} for error in failures]
        finalize_manifest(manifest, output_root)
        print("FN_CACTI_FLOW_FAILED", file=sys.stderr)
        return 1
    logic_area, logic_error = refresh_logic_area(manifest["run_kind"])
    if logic_error is not None or logic_area is None:
        manifest["status"] = "FLOW_FAILED"
        manifest["blockers"] = [
            {
                "code": "CURRENT_LOGIC_AREA_REFRESH_FAILED",
                "detail": logic_error or "logic area refresh did not return evidence",
            }
        ]
        finalize_manifest(manifest, output_root)
        print("FN_CACTI_FLOW_FAILED", file=sys.stderr)
        return 1
    manifest["logic_area"] = logic_area
    manifest["memory_inclusive_area"] = memory_inclusive_area(manifest["targets"], logic_area)
    manifest["status"] = PROXY_STATUS
    finalize_manifest(manifest, output_root)
    print("FN_CACTI_MEMORY_PPA_COMPLETE_ANALYTICAL_PROXY")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=("small", "default", "all"), default="all")
    parser.add_argument("--replay", action="store_true", help="write replay evidence under reports/synthesis/fn_cacti/replay")
    return run(parser.parse_args(argv))


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
