#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Run T036S ASAP7/ABC 100 MHz timing estimates and enforce the target."""

import argparse
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys

import run_synth_area as area
import run_yosys_slang as sanity

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
REPORT_DIR = REPO_ROOT / "reports/synthesis"
RAW_DIR = REPORT_DIR / "raw"
CONSTRAINTS = REPO_ROOT / "synth/asap7_timing.constr"
ABC_SCRIPT = REPO_ROOT / "synth/asap7_timing.abc"
CLOCK_PORT = "clk"
CLOCK_PERIOD_PS = 10_000.0
CLOCK_FREQUENCY_MHZ = 1_000_000.0 / CLOCK_PERIOD_PS
LIBERTY_TIME_UNIT = "1ps"
INPUT_DRIVER = "BUFx2_ASAP7_75t_R"
OUTPUT_LOAD_FF = 1.0
TREE_ESTIMATION_RATIO = 10
VALID_TIMING_STATUSES = {
    "ABC_LIBERTY_COMBINATIONAL_TIMING_ESTIMATE",
    "ABC_LIBERTY_COMBINATIONAL_TIMING_ESTIMATE_PARTIAL_MEMORY_UNMODELED",
}

DELAY_RE = re.compile(r"\bDelay\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*ps\b")
AREA_RE = re.compile(r"\bArea\s*=\s*([0-9]+(?:\.[0-9]+)?)\b")
STARTPOINT_RE = re.compile(
    r"\bStart-?point\s*=\s*(.+?)(?:\s+End-?point\s*=|$)", re.IGNORECASE
)
ENDPOINT_RE = re.compile(r"\bEnd-?point\s*=\s*(.+?)\s*$", re.IGNORECASE)


def run_command(command: list[str]) -> tuple[int, str]:
    completed = subprocess.run(
        command,
        cwd=REPO_ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return completed.returncode, completed.stdout


def run_command_to_log(command: list[str], log_path: pathlib.Path) -> int:
    with log_path.open("w", encoding="utf-8") as log:
        completed = subprocess.run(
            command,
            cwd=REPO_ROOT,
            check=False,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
        )
    return completed.returncode


def input_snapshot(rtl_files: list[str]) -> dict[str, str]:
    """Hash every durable input whose contents can affect the timing result."""
    return {
        "source_filelist_sha256": area.sha256(sanity.FILELIST),
        "source_list_sha256": hashlib.sha256(
            ("\n".join(rtl_files) + "\n").encode("utf-8")
        ).hexdigest(),
        "source_contents_sha256": sanity.sha256_sources(rtl_files),
        "liberty_sha256": area.sha256(area.ASAP7_LIBERTY),
        "manifest_sha256": area.sha256(area.ASAP7_MANIFEST),
        "constraint_file_sha256": area.sha256(CONSTRAINTS),
        "abc_script_sha256": area.sha256(ABC_SCRIPT),
    }


def sha256_if_file(path: pathlib.Path) -> str | None:
    return area.sha256(path) if path.is_file() else None


def yosys_script(target: str, rtl_files: list[str], paths: dict[str, pathlib.Path]) -> str:
    cfg = sanity.TARGETS[target]
    relative = {name: path.relative_to(REPO_ROOT).as_posix() for name, path in paths.items()}
    return "\n".join(
        [
            f"# Auto-generated by scripts/run_synth_timing.py for T036S target {target}.",
            "# ASAP7 v28 7.5-track RVT/TT NLDM combinational timing estimate.",
            "plugin -i slang",
            sanity.read_slang_cmd(target, rtl_files),
            f"hierarchy -check -top {cfg['top']}",
            "proc",
            "flatten",
            "opt",
            "memory_collect",
            "techmap */t:* */t:$mem_v2 %d",
            "opt",
            "techmap */t:* */t:$mem_v2 %d",
            "opt",
            "dffunmap",
            f"dfflibmap -liberty {relative['liberty']}",
            "abc -fast "
            f"-D {CLOCK_PERIOD_PS:g} "
            f"-script {relative['abc_script']} "
            f"-constr {relative['constraints']} "
            f"-liberty {relative['liberty']}",
            "clean",
            f"tee -o {relative['stat']} stat -json -liberty {relative['liberty']}",
            f"stat -liberty {relative['liberty']}",
            "",
        ]
    )


def extract_stime_section(output: str) -> list[str]:
    sections: list[list[str]] = []
    current: list[str] | None = None
    for line in output.splitlines():
        is_abc = line.startswith("ABC:")
        starts_stime = is_abc and (
            "stime -p" in line or "WireLoad" in line or DELAY_RE.search(line) is not None
        )
        if starts_stime and current is None:
            current = []
        if current is not None:
            if is_abc:
                current.append(line)
            elif current:
                sections.append(current)
                current = None
    if current:
        sections.append(current)
    timed = [section for section in sections if any(DELAY_RE.search(line) for line in section)]
    return timed[-1] if timed else []


def parse_stime(output: str) -> dict[str, object]:
    section = extract_stime_section(output)
    delay_ps = None
    mapped_area = None
    startpoint = None
    endpoint = None
    for line in section:
        delay_match = DELAY_RE.search(line)
        area_match = AREA_RE.search(line)
        start_match = STARTPOINT_RE.search(line)
        end_match = ENDPOINT_RE.search(line)
        if delay_match:
            delay_ps = float(delay_match.group(1))
        if area_match:
            mapped_area = float(area_match.group(1))
        if start_match:
            startpoint = start_match.group(1)
        if end_match:
            endpoint = end_match.group(1)
    path_points = sum(line.startswith("ABC: Path ") for line in section)
    reciprocal_mhz = 1_000_000.0 / delay_ps if delay_ps and delay_ps > 0 else None
    return {
        "available": delay_ps is not None,
        "estimated_combinational_delay_ps": delay_ps,
        "delay_reciprocal_mhz": reciprocal_mhz,
        "comparison_margin_ps": CLOCK_PERIOD_PS - delay_ps if delay_ps is not None else None,
        "abc_mapped_area": mapped_area,
        "startpoint": startpoint,
        "endpoint": endpoint,
        "path_point_count": path_points,
        "critical_path_lines": section,
    }


def write_critical_path_report(
    path: pathlib.Path,
    target: str,
    tool_version: str,
    status: str,
    timing: dict[str, object],
    memory_cells: object,
) -> None:
    cfg = sanity.TARGETS[target]
    lines = [
        "T036S ASAP7/ABC 100 MHz critical-path estimate",
        f"target: {target}",
        f"top: {cfg['top']}",
        f"parameters: {json.dumps(cfg['parameters'], sort_keys=True)}",
        f"status: {status}",
        f"tool: {tool_version}",
        f"clock_port: {CLOCK_PORT}",
        f"comparison_period_ps: {CLOCK_PERIOD_PS:g}",
        f"comparison_frequency_mhz: {CLOCK_FREQUENCY_MHZ:g}",
        f"liberty_time_unit: {LIBERTY_TIME_UNIT}",
        "constraint_interpretation: ABC mapping delay target and comparison baseline; not SDC",
        f"input_driver: {INPUT_DRIVER}",
        f"output_load_ff: {OUTPUT_LOAD_FF:g}",
        f"high_fanout_tree_estimation_ratio: {TREE_ESTIMATION_RATIO}",
        "liberty_corner: RVT_TT NLDM, nominal 0.7 V, 25 C",
        f"unmodeled_memory_cells: {memory_cells}",
        "critical_module: cgra_top (flattened before ABC mapping)",
        "limitations: combinational standard-cell delay only; sequential timing arcs, SRAM, wires, clock tree, parasitics, variation, placement, and routing are not modeled",
        "",
        f"ABC stime -X {TREE_ESTIMATION_RATIO} -p output:",
    ]
    section = timing.get("critical_path_lines", [])
    if isinstance(section, list) and section:
        lines.extend(str(line) for line in section)
    else:
        lines.append("<timing metric unavailable; inspect the matching full Yosys log>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_missing_prerequisite(target: str, finding: str) -> int:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    basename = f"asap7_timing_{target}"
    for suffix in (".log", ".ys", "_stat.json"):
        (RAW_DIR / f"{basename}{suffix}").unlink(missing_ok=True)
    report_path = RAW_DIR / f"{basename}_critical_path.rpt"
    record = {
        "schema": "cgra.asap7_timing_report.v1",
        "target": target,
        "status": "PREREQUISITE_MISSING",
        "repair_finding": finding,
        "critical_path_report": report_path.relative_to(REPO_ROOT).as_posix(),
    }
    report_path.write_text(
        f"T036S timing report unavailable\ntarget: {target}\nstatus: PREREQUISITE_MISSING\nrepair_finding: {finding}\n",
        encoding="utf-8",
    )
    (RAW_DIR / f"{basename}.json").write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"{target}: {finding}", file=sys.stderr)
    return 1


def configuration_error() -> str | None:
    abc_lines = ABC_SCRIPT.read_text(encoding="utf-8").splitlines()
    expected_stime = f"stime -X {TREE_ESTIMATION_RATIO} -p"
    mapping_targets = []
    for line in abc_lines:
        match = re.match(r"^\s*(?:map|&nf)\b.*?\s-D\s+([0-9]+(?:\.[0-9]+)?)\s*$", line)
        if match:
            mapping_targets.append(float(match.group(1)))
    if mapping_targets != [CLOCK_PERIOD_PS] or expected_stime not in abc_lines:
        return (
            "ABC script does not match the recorded delay target or high-fanout "
            "tree-estimation ratio."
        )
    constraint_lines = CONSTRAINTS.read_text(encoding="utf-8").splitlines()
    expected_constraints = [
        f"set_driving_cell {INPUT_DRIVER}",
        f"set_load {OUTPUT_LOAD_FF:.1f}",
    ]
    if constraint_lines != expected_constraints:
        return "ABC constraint file does not match the recorded driver/load assumptions."
    liberty_text = area.ASAP7_LIBERTY.read_text(encoding="utf-8")
    unit_match = re.search(r'^\s*time_unit\s*:\s*"([^"]+)"\s*;', liberty_text, re.MULTILINE)
    if unit_match is None or unit_match.group(1) != LIBERTY_TIME_UNIT:
        actual = unit_match.group(1) if unit_match is not None else "missing"
        return (
            f"Liberty time_unit is {actual}, expected {LIBERTY_TIME_UNIT}; "
            "ABC delay and comparison units are inconsistent."
        )
    return None


def run_target(target: str) -> int:
    prerequisites = (area.ASAP7_LIBERTY, area.ASAP7_MANIFEST, CONSTRAINTS, ABC_SCRIPT)
    missing = [path.relative_to(REPO_ROOT).as_posix() for path in prerequisites if not path.exists()]
    if missing:
        return write_missing_prerequisite(
            target, "missing timing prerequisite(s): " + ", ".join(missing)
        )
    yosys = shutil.which("yosys")
    if yosys is None:
        return write_missing_prerequisite(
            target, "yosys is missing; source ../oss-cad-suite/environment and retry."
        )
    try:
        rtl_files = sanity.read_filelist(sanity.FILELIST)
    except ValueError as error:
        return write_missing_prerequisite(target, str(error))
    try:
        pre_run_inputs = input_snapshot(rtl_files)
    except OSError as error:
        return write_missing_prerequisite(target, f"cannot hash timing input: {error}")
    manifest = area.load_json(area.ASAP7_MANIFEST) or {}
    config_error = configuration_error()
    if config_error:
        return write_missing_prerequisite(target, config_error)
    try:
        if input_snapshot(rtl_files) != pre_run_inputs:
            return write_missing_prerequisite(
                target, "timing inputs changed during preflight validation; retry."
            )
    except OSError as error:
        return write_missing_prerequisite(target, f"cannot recheck timing input: {error}")

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    basename = f"asap7_timing_{target}"
    paths = {
        "liberty": area.ASAP7_LIBERTY,
        "constraints": CONSTRAINTS,
        "abc_script": ABC_SCRIPT,
        "script": RAW_DIR / f"{basename}.ys",
        "stat": RAW_DIR / f"{basename}_stat.json",
        "critical_path": RAW_DIR / f"{basename}_critical_path.rpt",
    }
    for stale_path in (
        paths["stat"],
        paths["critical_path"],
        RAW_DIR / f"{basename}.json",
    ):
        stale_path.unlink(missing_ok=True)
    paths["script"].write_text(yosys_script(target, rtl_files, paths), encoding="utf-8")
    command = [yosys, "-Q", "-s", paths["script"].relative_to(REPO_ROOT).as_posix()]
    log_path = RAW_DIR / f"{basename}.log"
    returncode = run_command_to_log(command, log_path)
    output = log_path.read_text(encoding="utf-8")
    timing = parse_stime(output)
    delay_target_met = bool(
        timing["available"]
        and timing["estimated_combinational_delay_ps"] <= CLOCK_PERIOD_PS
    )
    resource_summary = area.stat_summary(paths["stat"], sanity.TARGETS[target]["top"])
    residual_types = resource_summary["unmapped_cell_types"]
    residual_memory_only = bool(residual_types) and all(
        "mem" in name.lower() for name in residual_types
    )

    try:
        post_run_inputs = input_snapshot(rtl_files)
        inputs_changed = post_run_inputs != pre_run_inputs
    except OSError:
        inputs_changed = True

    if returncode != 0:
        status = "TIMING_FLOW_FAILED"
        finding = "Yosys/ABC timing flow did not complete; inspect the matching raw log."
    elif inputs_changed:
        status = "TIMING_INPUT_CHANGED_DURING_RUN"
        finding = "One or more hashed timing inputs changed while Yosys/ABC was running; retry."
    elif not timing["available"]:
        status = "TIMING_METRIC_UNSUPPORTED_BY_SELECTED_FLOW"
        finding = "ABC completed without a parseable stime delay; inspect the raw log."
    elif not resource_summary["stat_available"]:
        status = "TIMING_FLOW_FAILED_STAT_UNAVAILABLE"
        finding = "Mapped stat JSON is missing or invalid; mapping completeness is unproven."
    elif resource_summary["unmapped_cells"] == 0:
        status = "ABC_LIBERTY_COMBINATIONAL_TIMING_ESTIMATE"
        finding = None
    elif residual_memory_only:
        status = "ABC_LIBERTY_COMBINATIONAL_TIMING_ESTIMATE_PARTIAL_MEMORY_UNMODELED"
        finding = (
            "ASAP7 standard-cell timing excludes inferred $mem_v2 storage cells because "
            "no SRAM timing model was selected."
        )
    else:
        status = "TIMING_FLOW_FAILED_UNMAPPED_LOGIC"
        finding = "Technology mapping left non-memory Yosys cells; timing is incomplete."
    timing_target_met = delay_target_met and status in VALID_TIMING_STATUSES

    version = run_command([yosys, "-V"])[1].strip()
    write_critical_path_report(
        paths["critical_path"],
        target,
        version,
        status,
        timing,
        resource_summary["memory_cells"],
    )
    record = {
        "schema": "cgra.asap7_timing_report.v1",
        "target": target,
        "top": sanity.TARGETS[target]["top"],
        "parameters": sanity.TARGETS[target]["parameters"],
        "define": "SYNTHESIS",
        "source_filelist": sanity.FILELIST.relative_to(REPO_ROOT).as_posix(),
        "source_filelist_sha256": pre_run_inputs["source_filelist_sha256"],
        "source_list_sha256": pre_run_inputs["source_list_sha256"],
        "source_contents_sha256": pre_run_inputs["source_contents_sha256"],
        "technology": {
            "name": "ASAP7 7nm predictive PDK",
            "standard_cell_library": "asap7sc7p5t_28",
            "corner": manifest.get("corner"),
            "liberty_model": manifest.get("liberty_model"),
            "nominal_voltage_v": 0.7,
            "nominal_temperature_c": 25,
            "liberty_time_unit": LIBERTY_TIME_UNIT,
            "repository": manifest.get("repository"),
            "repository_revision": manifest.get("repository_revision"),
            "standard_cell_revision": manifest.get("standard_cell_revision"),
            "liberty": paths["liberty"].relative_to(REPO_ROOT).as_posix(),
            "liberty_sha256": pre_run_inputs["liberty_sha256"],
            "manifest_sha256": pre_run_inputs["manifest_sha256"],
        },
        "tool": {
            "yosys_path": yosys,
            "yosys_version": version,
            "timing_engine": f"ABC stime -X {TREE_ESTIMATION_RATIO} -p invoked by Yosys abc",
            "openroad_path": shutil.which("openroad"),
            "openroad_status": "NOT_RUN_TOOL_UNAVAILABLE"
            if shutil.which("openroad") is None
            else "NOT_RUN_NO_PHYSICAL_BACKEND_REQUIRED",
        },
        "clock_assumption": {
            "port": CLOCK_PORT,
            "comparison_period_ps": CLOCK_PERIOD_PS,
            "comparison_frequency_mhz": CLOCK_FREQUENCY_MHZ,
            "abc_delay_target_ps": CLOCK_PERIOD_PS,
            "sdc_applied": False,
            "interpretation": (
                "ABC mapping target and comparison baseline only; Yosys does not apply "
                "an SDC clock in this flow, so the margin is not setup slack."
            ),
        },
        "target_status": "LOGIC_ONLY_TIMING_TARGET_MET"
        if timing_target_met
        else "LOGIC_ONLY_TIMING_TARGET_MISSED",
        "boundary_assumption": {
            "constraint_file": paths["constraints"].relative_to(REPO_ROOT).as_posix(),
            "constraint_file_sha256": pre_run_inputs["constraint_file_sha256"],
            "abc_script": paths["abc_script"].relative_to(REPO_ROOT).as_posix(),
            "abc_script_sha256": pre_run_inputs["abc_script_sha256"],
            "input_driver_cell": INPUT_DRIVER,
            "output_load_ff": OUTPUT_LOAD_FF,
            "high_fanout_tree_estimation_ratio": TREE_ESTIMATION_RATIO,
        },
        "reset_assumption": {
            "port": "rst_n",
            "polarity": "active_low",
            "sampling": "synchronous",
        },
        "command": command,
        "script": paths["script"].relative_to(REPO_ROOT).as_posix(),
        "script_sha256": sha256_if_file(paths["script"]),
        "raw_log": log_path.relative_to(REPO_ROOT).as_posix(),
        "raw_log_sha256": sha256_if_file(log_path),
        "raw_stat": paths["stat"].relative_to(REPO_ROOT).as_posix(),
        "raw_stat_sha256": sha256_if_file(paths["stat"]),
        "critical_path_report": paths["critical_path"].relative_to(REPO_ROOT).as_posix(),
        "critical_path_report_sha256": sha256_if_file(paths["critical_path"]),
        "returncode": returncode,
        "input_snapshot": pre_run_inputs,
        "status": status,
        "repair_finding": finding,
        "summary": {
            **{key: value for key, value in timing.items() if key != "critical_path_lines"},
            "delay_unit": "ps",
            "timing_target_met": timing_target_met,
            "stat_available": resource_summary["stat_available"],
            "critical_module": "cgra_top (flattened)",
            "memory_cells_unmodeled": resource_summary["memory_cells"],
            "mapped_cells": resource_summary["mapped_cells"],
            "register_cells": resource_summary["register_cells"],
        },
        "limitations": [
            "ABC stime covers mapped combinational standard-cell delay with the recorded I/O boundary and high-fanout tree-estimation assumptions.",
            "Sequential clock-to-Q, setup/hold, and recovery/removal checks are not included.",
            "Residual $mem_v2 cells have no SRAM macro or timing model.",
            "No placement, routing, extracted parasitics, clock tree, OCV, or signoff analysis is included.",
            "The reciprocal of delay is a logic-only comparison metric, not achieved Fmax or timing closure.",
        ],
    }
    (RAW_DIR / f"{basename}.json").write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"{target}: {status}")
    invalid = {
        "TIMING_FLOW_FAILED",
        "TIMING_METRIC_UNSUPPORTED_BY_SELECTED_FLOW",
        "TIMING_FLOW_FAILED_UNMAPPED_LOGIC",
        "TIMING_FLOW_FAILED_STAT_UNAVAILABLE",
        "TIMING_INPUT_CHANGED_DURING_RUN",
    }
    return 1 if status in invalid or not timing_target_met else 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=("small", "default", "all"), default="all")
    args = parser.parse_args(argv)
    targets = ("small", "default") if args.target == "all" else (args.target,)
    results = [run_target(target) for target in targets]
    return 0 if not any(results) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
