// SPDX-License-Identifier: MIT
`timescale 1ns/1ps

module cgra_pkg_tb;
  import cgra_pkg::*;

  task automatic expect_int_raw(input string name, input int actual, input int expected);
    begin
      if (actual !== expected) begin
        $error("%s: expected %0d, got %0d", name, expected, actual);
        $finish;
      end
    end
  endtask

`define EXPECT_INT(name, actual, expected) expect_int_raw(name, int'(actual), expected)

  initial begin
    `EXPECT_INT("ARRAY_ROWS", ARRAY_ROWS, 4);
    `EXPECT_INT("ARRAY_COLS", ARRAY_COLS, 4);
    `EXPECT_INT("DATA_WIDTH", DATA_WIDTH, 32);
    `EXPECT_INT("PRED_WIDTH", PRED_WIDTH, 1);
    `EXPECT_INT("DATA_RF_DEPTH", DATA_RF_DEPTH, 16);
    `EXPECT_INT("PRED_RF_DEPTH", PRED_RF_DEPTH, 16);
    `EXPECT_INT("CONST_MEM_DEPTH", CONST_MEM_DEPTH, 16);
    `EXPECT_INT("CTRL_MEM_DEPTH", CTRL_MEM_DEPTH, 256);
    `EXPECT_INT("SCRATCHPAD_DEPTH", SCRATCHPAD_DEPTH, 4096);
    `EXPECT_INT("SHARED_MEM_PORTS", SHARED_MEM_PORTS, 4);
    `EXPECT_INT("MESH_HOP_LATENCY", MESH_HOP_LATENCY, 1);
    `EXPECT_INT("LOAD_LATENCY", LOAD_LATENCY, 2);
    `EXPECT_INT("CONTROL_WORD_ALIGN", CONTROL_WORD_ALIGN, 32);

    `EXPECT_INT("DATA_RF_ADDR_WIDTH", DATA_RF_ADDR_WIDTH, 4);
    `EXPECT_INT("PRED_RF_ADDR_WIDTH", PRED_RF_ADDR_WIDTH, 4);
    `EXPECT_INT("CONST_ADDR_WIDTH", CONST_ADDR_WIDTH, 4);
    `EXPECT_INT("CTRL_PC_WIDTH", CTRL_PC_WIDTH, 8);
    `EXPECT_INT("SCRATCHPAD_ADDR_WIDTH", SCRATCHPAD_ADDR_WIDTH, 12);

    `EXPECT_INT("OP_NOP", OP_NOP, 0);
    `EXPECT_INT("OP_PASS", OP_PASS, 1);
    `EXPECT_INT("OP_ADD", OP_ADD, 2);
    `EXPECT_INT("OP_SUB", OP_SUB, 3);
    `EXPECT_INT("OP_MUL", OP_MUL, 4);
    `EXPECT_INT("OP_AND", OP_AND, 5);
    `EXPECT_INT("OP_OR", OP_OR, 6);
    `EXPECT_INT("OP_XOR", OP_XOR, 7);
    `EXPECT_INT("OP_SHL", OP_SHL, 8);
    `EXPECT_INT("OP_LSHR", OP_LSHR, 9);
    `EXPECT_INT("OP_SELECT", OP_SELECT, 10);
    `EXPECT_INT("OP_CMP_EQ", OP_CMP_EQ, 16);
    `EXPECT_INT("OP_CMP_NE", OP_CMP_NE, 17);
    `EXPECT_INT("OP_CMP_ULT", OP_CMP_ULT, 18);
    `EXPECT_INT("OP_CMP_ULE", OP_CMP_ULE, 19);
    `EXPECT_INT("OP_PPASS", OP_PPASS, 32);
    `EXPECT_INT("OP_PNOT", OP_PNOT, 33);
    `EXPECT_INT("OP_PAND", OP_PAND, 34);
    `EXPECT_INT("OP_POR", OP_POR, 35);

    `EXPECT_INT("DATA_SRC_RF_A", DATA_SRC_RF_A, 0);
    `EXPECT_INT("DATA_SRC_RF_B", DATA_SRC_RF_B, 1);
    `EXPECT_INT("DATA_SRC_NORTH_DATA_IN", DATA_SRC_NORTH_DATA_IN, 2);
    `EXPECT_INT("DATA_SRC_SOUTH_DATA_IN", DATA_SRC_SOUTH_DATA_IN, 3);
    `EXPECT_INT("DATA_SRC_EAST_DATA_IN", DATA_SRC_EAST_DATA_IN, 4);
    `EXPECT_INT("DATA_SRC_WEST_DATA_IN", DATA_SRC_WEST_DATA_IN, 5);
    `EXPECT_INT("DATA_SRC_CONST_DATA", DATA_SRC_CONST_DATA, 6);
    `EXPECT_INT("DATA_SRC_LSU_LOAD_DATA", DATA_SRC_LSU_LOAD_DATA, 7);
    `EXPECT_INT("DATA_SRC_ZERO", DATA_SRC_ZERO, 8);

    `EXPECT_INT("PRED_SRC_RF_A", PRED_SRC_RF_A, 0);
    `EXPECT_INT("PRED_SRC_RF_B", PRED_SRC_RF_B, 1);
    `EXPECT_INT("PRED_SRC_NORTH_PRED_IN", PRED_SRC_NORTH_PRED_IN, 2);
    `EXPECT_INT("PRED_SRC_SOUTH_PRED_IN", PRED_SRC_SOUTH_PRED_IN, 3);
    `EXPECT_INT("PRED_SRC_EAST_PRED_IN", PRED_SRC_EAST_PRED_IN, 4);
    `EXPECT_INT("PRED_SRC_WEST_PRED_IN", PRED_SRC_WEST_PRED_IN, 5);
    `EXPECT_INT("PRED_SRC_CONST_TRUE", PRED_SRC_CONST_TRUE, 6);
    `EXPECT_INT("PRED_SRC_CONST_FALSE", PRED_SRC_CONST_FALSE, 7);

    `EXPECT_INT("DATA_ROUTE_SRC_NONE", DATA_ROUTE_SRC_NONE, 0);
    `EXPECT_INT("DATA_ROUTE_SRC_NORTH_DATA_IN", DATA_ROUTE_SRC_NORTH_DATA_IN, 1);
    `EXPECT_INT("DATA_ROUTE_SRC_SOUTH_DATA_IN", DATA_ROUTE_SRC_SOUTH_DATA_IN, 2);
    `EXPECT_INT("DATA_ROUTE_SRC_EAST_DATA_IN", DATA_ROUTE_SRC_EAST_DATA_IN, 3);
    `EXPECT_INT("DATA_ROUTE_SRC_WEST_DATA_IN", DATA_ROUTE_SRC_WEST_DATA_IN, 4);
    `EXPECT_INT("DATA_ROUTE_SRC_FU_DATA", DATA_ROUTE_SRC_FU_DATA, 5);
    `EXPECT_INT("DATA_ROUTE_SRC_RF_A", DATA_ROUTE_SRC_RF_A, 6);
    `EXPECT_INT("DATA_ROUTE_SRC_RF_B", DATA_ROUTE_SRC_RF_B, 7);
    `EXPECT_INT("DATA_ROUTE_SRC_CONST_DATA", DATA_ROUTE_SRC_CONST_DATA, 8);
    `EXPECT_INT("DATA_ROUTE_SRC_LSU_LOAD_DATA", DATA_ROUTE_SRC_LSU_LOAD_DATA, 9);
    `EXPECT_INT("DATA_ROUTE_SRC_ZERO", DATA_ROUTE_SRC_ZERO, 10);

    `EXPECT_INT("PRED_ROUTE_SRC_NONE", PRED_ROUTE_SRC_NONE, 0);
    `EXPECT_INT("PRED_ROUTE_SRC_NORTH_PRED_IN", PRED_ROUTE_SRC_NORTH_PRED_IN, 1);
    `EXPECT_INT("PRED_ROUTE_SRC_SOUTH_PRED_IN", PRED_ROUTE_SRC_SOUTH_PRED_IN, 2);
    `EXPECT_INT("PRED_ROUTE_SRC_EAST_PRED_IN", PRED_ROUTE_SRC_EAST_PRED_IN, 3);
    `EXPECT_INT("PRED_ROUTE_SRC_WEST_PRED_IN", PRED_ROUTE_SRC_WEST_PRED_IN, 4);
    `EXPECT_INT("PRED_ROUTE_SRC_FU_PRED", PRED_ROUTE_SRC_FU_PRED, 5);
    `EXPECT_INT("PRED_ROUTE_SRC_RF_A", PRED_ROUTE_SRC_RF_A, 6);
    `EXPECT_INT("PRED_ROUTE_SRC_RF_B", PRED_ROUTE_SRC_RF_B, 7);
    `EXPECT_INT("PRED_ROUTE_SRC_CONST_TRUE", PRED_ROUTE_SRC_CONST_TRUE, 8);
    `EXPECT_INT("PRED_ROUTE_SRC_CONST_FALSE", PRED_ROUTE_SRC_CONST_FALSE, 9);

    `EXPECT_INT("LSU_OP_NONE", LSU_OP_NONE, 0);
    `EXPECT_INT("LSU_OP_LOAD", LSU_OP_LOAD, 1);
    `EXPECT_INT("LSU_OP_STORE", LSU_OP_STORE, 2);
    `EXPECT_INT("LSU_OP_RESERVED", LSU_OP_RESERVED, 3);

    `EXPECT_INT("EXEC_CTRL_WIDTH", EXEC_CTRL_WIDTH, 38);
    `EXPECT_INT("DATA_RF_CTRL_WIDTH", DATA_RF_CTRL_WIDTH, 14);
    `EXPECT_INT("PRED_RF_CTRL_WIDTH", PRED_RF_CTRL_WIDTH, 14);
    `EXPECT_INT("DATA_ROUTE_CTRL_WIDTH", DATA_ROUTE_CTRL_WIDTH, 20);
    `EXPECT_INT("PRED_ROUTE_CTRL_WIDTH", PRED_ROUTE_CTRL_WIDTH, 20);
    `EXPECT_INT("CONST_CTRL_WIDTH", CONST_CTRL_WIDTH, 4);
    `EXPECT_INT("LSU_CTRL_WIDTH", LSU_CTRL_WIDTH, 16);
    `EXPECT_INT("CONTROL_WORD_RAW_WIDTH", CONTROL_WORD_RAW_WIDTH, 126);
    `EXPECT_INT("CONTROL_WORD_PHYSICAL_WIDTH", CONTROL_WORD_PHYSICAL_WIDTH, 128);
    `EXPECT_INT("CONTROL_WORD_CHUNKS", CONTROL_WORD_CHUNKS, 4);

    $display("CGRA package constants and enum test passed");
    $finish;
  end
endmodule : cgra_pkg_tb
